version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "jobsearch/backend"
    ports:
      - "9000:9000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "jobsearch/frontend"
    ports:
      - "3000:3000"
    # links:
    #   - "backend"